env: "local"
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "root"
  dbname: "bookshelves"
  sslmode: "disable"
http_server: 
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s